// <auto-generated />
namespace POS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class columnadded_inuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnadded_inuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202105200627128_columnadded_inuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
