// <auto-generated />
namespace POS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pdfPassword_in_shop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pdfPassword_in_shop));
        
        string IMigrationMetadata.Id
        {
            get { return "202106141438359_pdfPassword_in_shop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
