// <auto-generated />
namespace POS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sales_branch_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sales_branch_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202107021005126_sales_branch_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
