// <auto-generated />
namespace POS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class calculate_vat_ref_in_bill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(calculate_vat_ref_in_bill));
        
        string IMigrationMetadata.Id
        {
            get { return "202107090757462_calculate_vat_ref_in_bill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
