name: .NET Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
      -uses: actions/checkout@main
      -name: Setup .NET
       uses: actions/setup-dotnet@v2
      with:
        doenet-version: 4.7.x
     -name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    -name: Restore Nuget Packages
     run: nuget restore POSSystem.sln
      -name: Build with dotnet
       run: dotnet build --configuration Release
      -name: Test
       runt: dotnet test --veerbosity normal
    
